-- noname-crm schema
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  level TINYINT(4) NOT NULL DEFAULT 1,
  phone VARCHAR(255) DEFAULT '',
  email VARCHAR(255) DEFAULT '',
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS personel;
CREATE TABLE personel (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT '',
  phone VARCHAR(255) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS jobs;
CREATE TABLE jobs (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS clients;
CREATE TABLE clients (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  vk_number VARCHAR(255) DEFAULT NULL,
  vk_name VARCHAR(255) DEFAULT NULL,
  address VARCHAR(1000) DEFAULT NULL,
  fullname VARCHAR(255) NOT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS offers;
CREATE TABLE offers (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  client_id INT(11) NOT NULL,
  offer_id INT(11) NOT NULL,
  offer_status INT(11) NOT NULL DEFAULT 0,
  offer_type INT(11) DEFAULT NULL,
  offer_title VARCHAR(255) NOT NULL,
  offer_text TEXT,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  offer_date DATE NOT NULL,
  final_date DATE NOT NULL,
  user_id INT(11) DEFAULT NULL,
  main_offer_id INT(11) DEFAULT NULL,
  INDEX (offer_id),
  INDEX (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS offers_matters;
CREATE TABLE offers_matters (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ordering INT(11) NOT NULL DEFAULT 0,
  offer_id INT(11) NOT NULL,
  matter_title VARCHAR(255) NOT NULL,
  matter_description TEXT NOT NULL,
  matter_extra TEXT,
  matter_unit INT(11) NOT NULL DEFAULT 1,
  matter_old_price FLOAT DEFAULT NULL,
  matter_price FLOAT NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS agreements;
CREATE TABLE agreements (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  client_id INT(11) NOT NULL,
  offer_id INT(11) NOT NULL,
  agreement_type INT(11) NOT NULL,
  agreement_status INT(11) NOT NULL DEFAULT 0,
  agreement_title VARCHAR(255) NOT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  price FLOAT DEFAULT NULL,
  kdv INT(11) NOT NULL DEFAULT 20,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS agreements_matters;
CREATE TABLE agreements_matters (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ordering INT(11) NOT NULL DEFAULT 0,
  offer_id INT(11) NOT NULL,
  offer_matter_id INT(11) NOT NULL,
  matter_title VARCHAR(255) NOT NULL,
  matter_description TEXT NOT NULL,
  matter_extra TEXT,
  matter_unit INT(11) NOT NULL DEFAULT 1,
  matter_price FLOAT NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS projects;
CREATE TABLE projects (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  offer_id INT(11) NOT NULL,
  client_id INT(11) NOT NULL,
  personel_id INT(11) NOT NULL,
  status INT(11) NOT NULL DEFAULT 0,
  type INT(11) NOT NULL,
  title VARCHAR(255) NOT NULL,
  price INT(11) NOT NULL DEFAULT 0,
  kdv INT(11) NOT NULL DEFAULT 20,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  INDEX (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS projects_billings;
CREATE TABLE projects_billings (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  offer_id INT(11) NOT NULL,
  pay INT(11) NOT NULL DEFAULT 0,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (offer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS domains;
CREATE TABLE domains (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  base_id INT(11) NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  create_date DATE NOT NULL,
  status INT(11) NOT NULL DEFAULT 1,
  pay_status INT(2) NOT NULL DEFAULT 0,
  subscription INT(11) NOT NULL DEFAULT 1,
  fullname VARCHAR(255) DEFAULT '',
  phone VARCHAR(255) DEFAULT '',
  email VARCHAR(255) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS offer_templates;
CREATE TABLE offer_templates (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  offer_type INT(11) DEFAULT NULL,
  default_offer_title VARCHAR(255) DEFAULT NULL,
  default_offer_text TEXT,
  default_validity_days INT(11) NOT NULL DEFAULT 15,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS offer_template_matters;
CREATE TABLE offer_template_matters (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  template_id INT(11) NOT NULL,
  ordering INT(11) NOT NULL DEFAULT 0,
  matter_title VARCHAR(255) NOT NULL,
  matter_description TEXT NOT NULL,
  matter_extra TEXT,
  matter_unit INT(11) NOT NULL DEFAULT 1,
  matter_old_price FLOAT DEFAULT NULL,
  matter_price FLOAT NOT NULL DEFAULT 0,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS domain_pricing;
CREATE TABLE domain_pricing (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  monthly_price FLOAT NOT NULL DEFAULT 0,
  full_price FLOAT NOT NULL DEFAULT 0,
  kdv FLOAT NOT NULL DEFAULT 20
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
