-- noname-crm seed
-- admin user (password: admin123 - bcrypt hash will be generated by seed script)
INSERT INTO jobs (title) VALUES
  ('Web Tasarım'),
  ('Grafik Tasarım'),
  ('Video/Prodüksiyon'),
  ('Dijital Pazarlama'),
  ('Mobil Uygulama');

INSERT INTO domain_pricing (title, monthly_price, full_price, kdv) VALUES
  ('Standart', 5, 50, 20),
  ('Pro', 10, 100, 20),
  ('Premium', 20, 200, 20);

INSERT INTO personel (fullname, email, phone) VALUES
  ('Demo Personel', 'demo@noname.local', '');
